apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  type: NodePort  # albo LoadBalancer w chmurze
  selector:
    app: devops-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001   # lokalny port na maszynie